BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Base de donnée` (
	`Nom`	TEXT,
	`Marque`	TEXT,
	`Caution`	TEXT,
	`Etat`	TEXT,
	`Quantite`	TEXT,
	`categorie`	TEXT,
	`Disponible`	TEXT
);
INSERT INTO `Base de donnée` VALUES ('Micro Shure SM58','Shure','110.00','ok','4','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro Shure SM57','Shure','109.00','ok','2','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro Shure Beta 58A','Shure','180.00','ok','1','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro Shure 10A','Shure','-','ok','2','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro Shure PG81','Shure','140.00','ok','1','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro Superlux PRA-228A','Superlux','60.00','ok','2','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro Superlux PRA-218A','Superlux','60.00','ok','1','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro Sennheiser md421','Sennheiser','400.00','ok','1','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro Audio Technica MB6K','Audio technica','90.00','ok','1','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro Sennheiser e835','Sennheiser','99.00','ok','1','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro special grosse caisse','N/A','-','ok','1','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro Berhringer Ultravoice','Berhinger','-','ok','2','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Micro AKG D5','AKG','95.00','ok','1','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Sennheiser UHF Vocal Set fp 35 C EU','Sennheiser','269.00','?','1','Micro','-');
INSERT INTO `Base de donnée` VALUES ('Ampli QSC Audio RMX 850','QSC','450.00','ok','4','Ampli','-');
INSERT INTO `Base de donnée` VALUES ('Ampli QSC Audio RMX 1450','QSC','500.00','ok','3','Ampli','-');
INSERT INTO `Base de donnée` VALUES ('Ampli QSC Audio RMX 2450','QSC','800.00','ok','1','Ampli','-');
INSERT INTO `Base de donnée` VALUES ('Ampli STA Club 1503','STA','350.00','ok','1','Ampli','-');
INSERT INTO `Base de donnée` VALUES ('Table de mixage Allen & Heath GL2400','Allen&Heath','','ok','1','Table de mixage','-');
INSERT INTO `Base de donnée` VALUES ('Table Pioneer XDJ-RX + flight case','Pioneer','','ok','1','Table de mixage','-');
INSERT INTO `Base de donnée` VALUES ('Table Pioneer DJM 700','Pioneer','620.00','ok','1','Table de mixage','-');
INSERT INTO `Base de donnée` VALUES ('Table de mixage Behringer Xenyx X1204 USB','Behringer','130.00','ok','1','Table de mixage','-');
INSERT INTO `Base de donnée` VALUES ('Table de mixage Behringer DJX700','Berhringer','169.00','ok','1','Table de mixage','-');
INSERT INTO `Base de donnée` VALUES ('Table de mixage Mackie CFX 16','Mackie','716.00','ok','1','Table de mixage','-');
INSERT INTO `Base de donnée` VALUES ('Platine Denon SC 2900','Denon','560.00','ok','2','Platine','-');
INSERT INTO `Base de donnée` VALUES ('Filtre Behringer CX 2300','Behringer','70.00','ok','1','Effects','-');
INSERT INTO `Base de donnée` VALUES ('Equalizer EQ Crest CPQ 2131P','EQ Crest','300.00','ok','2','Egaliseur','-');
INSERT INTO `Base de donnée` VALUES ('Equalizer EQ Crest CPQ 2215P','EQ Crest','300.00','ok','1','Egaliseur','-');
INSERT INTO `Base de donnée` VALUES ('Compresseur + Gate dbx 266XL','DBX','180.00','ok','3','Effects','-');
INSERT INTO `Base de donnée` VALUES ('Reverb + Delay TC Electronics M350','TC electronics','200.00','ok','1','Effects','-');
INSERT INTO `Base de donnée` VALUES ('Cordial Multi 24 + Sac de transport','','480.00','ok','1','Effects','-');
INSERT INTO `Base de donnée` VALUES ('Line Splitter Palmer PLS 02','Palmer','222.00','ok','1','Effects','-');
INSERT INTO `Base de donnée` VALUES ('DI stereo Samson S-Direct Plus','Samson','40.00','ok','3','DI','-');
INSERT INTO `Base de donnée` VALUES ('DI Box AR116 BSS','','100.00','ok','1','DI','-');
INSERT INTO `Base de donnée` VALUES ('DI Alctron 120','','39.00','ok','2','DI','-');
INSERT INTO `Base de donnée` VALUES ('DI Millenium 66','','35.00','ok','1','DI','-');
INSERT INTO `Base de donnée` VALUES ('Ultra DI Pro Berhringer DI 4000','behringer','90.00','ok','1','DI','-');
INSERT INTO `Base de donnée` VALUES ('Millenium sp8 splitter','Millenium','98.00','ok','1','Effets','-');
INSERT INTO `Base de donnée` VALUES ('Enceintes Yamaha SM121V','Yahama','250.00','ok','2','Enceintes','-');
INSERT INTO `Base de donnée` VALUES ('Enceintes EV Sx 300','EV','650.00','ok','2','Enceintes','-');
INSERT INTO `Base de donnée` VALUES ('Enceintes D.A.S DS15','DAS','725.00','ok','2','Enceintes','-');
INSERT INTO `Base de donnée` VALUES ('Enceintes ALS QG-15','ALS','500.00','1 ok, 1 HS','2','Enceintes','-');
INSERT INTO `Base de donnée` VALUES ('Enceintes Sub ALS (500W)','Sub','400.00','ok','2','Enceintes','-');
INSERT INTO `Base de donnée` VALUES ('Caissons Atelier 33 /Haut-parleurs Eminence Sigma Pro 18A-2','Eminence','500.00','ok','4','Enceintes','-');
INSERT INTO `Base de donnée` VALUES ('Enceintes EV ELX 115','EV','340.00','ok','2','Enceintes','-');
INSERT INTO `Base de donnée` VALUES ('Enceinte active Yamaha DXR8','Yamaha','595.00','ok','1','Enceintes','-');
INSERT INTO `Base de donnée` VALUES ('Enceintes EV ZLX 12P','','378.00','ok','2','Enceintes','-');
INSERT INTO `Base de donnée` VALUES ('Enceinte active Solton MF 300A','Solton','285.00','ok','1','Enceintes','-');
INSERT INTO `Base de donnée` VALUES ('Enceinte JBL','JBL','519.00','ok','2','Enceintes','-');
INSERT INTO `Base de donnée` VALUES ('Scan ROBE 575 XT','ROBE','','4 ok / 1 HS','5','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Scan Nicols Pat HID','Nicols','350.00','ok','3','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Showtec Sunstrip Active DMX','Showtec','290.00','ok','2','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Botex MPX-405 Dimmer','Botex','140.00','ok','5','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Strobo Martin Atomic 3000','Martin atomic','700.00','ok','1','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Lumiere noire Nicols UV panel 363','Nicols','209.00','ok','1','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('G-Tech HighLase 250G','Highlase','790.00','ok','1','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Antari Z1200 II Fog Machine','Antari','300.00','ok','1','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('PAR (grand)','','50.00','10 ok, 5 sans lampe, 1 cable alim casse','15','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('PAR (petit)','','18.90','2 ok, 4 sans lampe','6','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('DTS Scena 300/500 MK2 PC Anti Halo','Scena','117.00','ok','2','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('DTS Scena 650/1000 MK2 PC Anti Halo','Scena','135.00','1 ok 3 lampe HS','4','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Stairville B5R Beam Moving Head 5R','Stairville','998.00','ok','2','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Boitier Sunlite suite 2 Basic Class','Sunlite','429.00','ok','2','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Controleur DMX Starway CHAMAN','Starway','35.00','?','1','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Controleur DMX Starway CHEYEN','Starway','40.00','?','1','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Channel dispatching Starway TIWA','Starway','49.00','?','1','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Channels dimming console Starway CHEYEN','Starway','190.00','?','1','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Pied de levage (grand) Alu Tech ALT 450','Alu tech','','ok','2','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Pied de levage (petit) Mobil Tech 4aF Mini','Mobil tech','200.00','ok','2','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Pad AKAI APC 40','AKAI','299.00','ok','1','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Rail portatif (2m)','','200.00','ok','3','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Boule a facettes','','-','ok','1','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('Antichute de charge 250 kg','','-','','2','Lumieres','-');
INSERT INTO `Base de donnée` VALUES ('','','','','','','-');
INSERT INTO `Base de donnée` VALUES ('> 9m','','','','19','XLR','-');
INSERT INTO `Base de donnée` VALUES ('< 9m','','','','39','XLR','-');
INSERT INTO `Base de donnée` VALUES ('Petits','','','','7','XLR','-');
INSERT INTO `Base de donnée` VALUES ('DMX (sans compter rail)','','','','26','DMX','-');
INSERT INTO `Base de donnée` VALUES ('','','','','','','-');
INSERT INTO `Base de donnée` VALUES ('XLR male','','','','?','XLR-Jack','-');
INSERT INTO `Base de donnée` VALUES ('XLR femelle','','','','8','XLR-Jack','-');
INSERT INTO `Base de donnée` VALUES ('Jack','','','','14','XLR-Jack','-');
INSERT INTO `Base de donnée` VALUES ('Speakon','','','','14','Speakon','-');
INSERT INTO `Base de donnée` VALUES ('','','','','','','-');
INSERT INTO `Base de donnée` VALUES ('Grandes','','','','2','Rallonges','-');
INSERT INTO `Base de donnée` VALUES ('Moyennes - petites','','','','19','Rallonges','-');
INSERT INTO `Base de donnée` VALUES ('Enrouleurs','','','','6','Rallonages','-');
INSERT INTO `Base de donnée` VALUES ('Alimentations','','','','44','Alims','-');
INSERT INTO `Base de donnée` VALUES ('Rallonges d''alimentations','','','','5','Rallonges d''alims','-');
INSERT INTO `Base de donnée` VALUES ('','','','','','','-');
INSERT INTO `Base de donnée` VALUES ('XLR -rca simple','','','','1','Autres','-');
INSERT INTO `Base de donnée` VALUES ('RCA doubles','','','','3','Autres','-');
INSERT INTO `Base de donnée` VALUES ('RCA simple','','','','2','Autres','-');
INSERT INTO `Base de donnée` VALUES ('RCA double- petit jack','','','','4','Autres','-');
INSERT INTO `Base de donnée` VALUES ('RCA double - double jack','','','','1','Autres','-');
COMMIT;
